new and improved authorized_keys generation script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,23 +1,94 @@
 #!/usr/bin/env sh
-# ColtonDRG's SSH Keystore
-# Script to install keys to a system.
+# ColtonDRG SSH Keystore
+# Script to generate authorized_keys file
+# This script is under the MIT License. You can do whatever you want with it!
 
-INSTALL_FILE=$HOME/.ssh/authorized_keys
+do_cd() {
+	cd "`dirname $0`"
+}
 
-if [ "$1" != "" ]; then
-	INSTALL_FILE=`readlink -f $1`
+build_vars() {
+SCRIPT_REV="v2"
+if [ "$INSTALL_FILE" = "" ]; then
+INSTALL_FILE="$HOME/.ssh/authorized_keys"
 fi
+SCRIPT_DOCUMENTATION="
+ColtonDRG SSH Keystore `git rev-parse --short HEAD`
+authorized_keys generation (install) script $SCRIPT_REV
+Usage: ./install [options]
+Available Options:
+  -help		Print this help message and exit
+  -auto		Don't confirm before overwriting authorized_keys
+  -pull		Update to the latest commit before updating
+  -cron		Same as -pull and -auto together. For use in cron jobs
+  -file <file>	Specify the location of the authorized_keys file.
+		Default is $HOME/.ssh/authorized_keys
+Use \`git pull\` to update the keys & scripts
+"
+}
 
-cd `dirname $0`
-echo "The ssh keys from commit `git rev-parse --short HEAD` will be installed."
-echo "The keys will be installed to $INSTALL_FILE"
-echo "If the commit is wrong, use \`git pull\` to update the repo."
-echo "If the installation location is wrong, use \`./install <authorized_keys>\`."
-echo "Also note that the contents of $INSTALL_FILE will be destroyed."
-echo "If these are correct, press [Enter]. Press [Ctrl+C] to cancel."
-read _
-echo "# Generated by ColtonDRG/ssh-keystore/install" > $INSTALL_FILE
-echo "# Generated from ColtonDRG/ssh-keystore commit `git rev-parse --short HEAD` on `date -u "+%Y/%m/%d %H:%M"`" >> $INSTALL_FILE
-echo "# Pull the latest changes and re-run the install script to update." >> $INSTALL_FILE
-echo "" >> $INSTALL_FILE
-cat *.pub >> $INSTALL_FILE
+get_options() {
+	case $1 in
+		-help|--help|help)
+			do_cd
+			build_vars
+			echo "$SCRIPT_DOCUMENTATION"
+			exit 0
+			;;
+		-file|--file|file)
+			shift
+			INSTALL_FILE="`readlink -f $1`"
+			shift
+			get_options $@
+			;;
+		-auto|--auto|auto)
+			OPT_NOCONFIRM="true"
+			shift
+			get_options $@
+			;;
+		-pull|--pull|pull)
+			OPT_DO_PULL="true"
+			shift
+			get_options $@
+			;;
+		-cron|--cron|cron)
+			OPT_NOCONFIRM="true"
+			OPT_DO_PULL="true"
+			shift
+			get_options $@
+			;;
+		"")
+			do_cd
+			build_vars
+			do_the_thing
+			;;
+		*)
+			echo "Invalid option: $1"
+			echo "Use \`./install -help\` to learn how to use the script."
+			exit 1
+			;;
+	esac
+}
+
+do_the_thing() {
+	if [ "$OPT_DO_PULL" = "true" ]; then
+		git pull
+	fi
+	echo "ColtonDRG SSH Keystore authorized_keys generation script $SCRIPT_REV"
+	echo "The keys from commit `git rev-parse --short HEAD` will be used to generate an authorized_keys file"
+	echo "The authorized_keys file generated will be placed at $INSTALL_FILE"
+	echo "Note that the existing contents of $INSTALL_FILE will be destroyed."
+	echo "For help on using this script, do \`./install -help\`"
+	if [ "$OPT_NOCONFIRM" != "true" ]; then
+		echo "If these are correct, press [Enter]. Press [Ctrl+C] to cancel."
+		read _
+	fi
+	echo "# authorized_keys generated by ColtonDRG SSH Keystore script $SCRIPT_REV (https://github.com/ColtonDRG/ssh-keystore)" > $INSTALL_FILE
+	echo "# Generated from ColtonDRG/ssh-keystore commit `git rev-parse --short HEAD` on `date -u +%Y/%m/%d\ %H:%M`" >> $INSTALL_FILE
+	echo >> $INSTALL_FILE
+	cat *.pub >> $INSTALL_FILE
+	echo "Process complete"
+	exit 0
+}
+
+get_options $@
