better filesystem handling

diff --git a/install b/install
--- a/install
+++ b/install
@@ -6,11 +6,11 @@
 {
 
 function do_cd() {
-	cd "`dirname $0`"
+	cd "$(dirname "$0")"
 }
 
 function build_vars() {
-SCRIPT_REV="v7"
+SCRIPT_REV="v8"
 if [ "$INSTALL_FILE" = "" ]; then
 INSTALL_FILE="$HOME/.ssh/authorized_keys"
 fi
@@ -40,7 +40,7 @@ function get_options() {
 			;;
 		-file|--file|file|-f)
 			shift
-			INSTALL_FILE="`readlink -f $1`"
+			INSTALL_FILE="$(readlink -m "$1")"
 			shift
 			get_options "$@"
 			;;
@@ -115,6 +115,16 @@ function do_the_thing() {
 	if [ "$OPT_NOCONFIRM" != "true" ]; then
 		echo "If these are correct, press [Enter]. Press [Ctrl+C] to cancel."
 		read _
+	fi
+	INSTALL_DIR=$(dirname "$INSTALL_FILE")
+	if [ ! -d "$INSTALL_DIR" ];then
+		echo "$INSTALL_DIR does not exist, creating it."
+		mkdir -p "$INSTALL_DIR" || { echo "Failed to create $INSTALL_DIR."; exit 4; }
+	fi
+	touch $INSTALL_FILE || { echo "Unable to write to $INSTALL_FILE."; exit 2; }
+	if [ ! -w $INSTALL_FILE ];then
+		echo "Unable to write to $INSTALL_FILE."
+		exit 2
 	fi
 	echo "# authorized_keys generated by ColtonDRG SSH Keystore script $SCRIPT_REV ($PROJECT_URL)" > $INSTALL_FILE
 	echo "# Generated from ColtonDRG/ssh-keystore commit `git rev-parse --short HEAD` on `date -u +%Y/%m/%d\ %H:%M`" >> $INSTALL_FILE
