better parsing & cleanup

diff --git a/install b/install
--- a/install
+++ b/install
@@ -10,13 +10,13 @@ function do_cd() {
 }
 
 function build_vars() {
-SCRIPT_REV="v8"
+SCRIPT_REV="v9"
 if [ "$INSTALL_FILE" = "" ]; then
 INSTALL_FILE="$HOME/.ssh/authorized_keys"
 fi
 PROJECT_URL="https://git.drg.li/ColtonDRG/ssh-keystore"
 SCRIPT_DOCUMENTATION="
-ColtonDRG SSH Keystore `git rev-parse --short HEAD` ($PROJECT_URL)
+ColtonDRG SSH Keystore $(git rev-parse --short HEAD) ($PROJECT_URL)
 authorized_keys generation (install) script $SCRIPT_REV
 Usage: ./install [options]
 Available Options:
@@ -32,7 +32,7 @@ Use \`git pull\` to update the keys & scripts
 
 function get_options() {
 	case $1 in
-		-help|--help|help|-h|"-?")
+		-help|--help|help|-h|"-?"|-version|--version|version|-v)
 			do_cd
 			build_vars
 			echo "$SCRIPT_DOCUMENTATION"
@@ -87,7 +87,6 @@ function get_md5() {
 
 function do_the_thing() {
 	if [ "$OPT_DO_PULL" = "true" ]; then
-		# This can cause some weird things to happen if the script changes during the pull. Perhaps the script should detect such changes and restart itself?
 		SCRIPT_MD5=$(get_md5 install)
 		git pull
 		if [ "$SCRIPT_MD5" = "no_md5_err" ];then
@@ -108,7 +107,7 @@ function do_the_thing() {
 		fi
 	fi
 	echo "ColtonDRG SSH Keystore authorized_keys generation script $SCRIPT_REV"
-	echo "The keys from commit `git rev-parse --short HEAD` will be used to generate an authorized_keys file"
+	echo "The keys from commit $(git rev-parse --short HEAD) will be used to generate an authorized_keys file"
 	echo "The authorized_keys file generated will be placed at $INSTALL_FILE"
 	echo "Note that the existing contents of $INSTALL_FILE will be destroyed."
 	echo "For help on using this script, do \`./install -help\`"
@@ -121,15 +120,15 @@ function do_the_thing() {
 		echo "$INSTALL_DIR does not exist, creating it."
 		mkdir -p "$INSTALL_DIR" || { echo "Failed to create $INSTALL_DIR."; exit 4; }
 	fi
-	touch $INSTALL_FILE || { echo "Unable to write to $INSTALL_FILE."; exit 2; }
-	if [ ! -w $INSTALL_FILE ];then
+	touch "$INSTALL_FILE" || { echo "Unable to write to $INSTALL_FILE."; exit 2; }
+	if [ ! -w "$INSTALL_FILE" ];then
 		echo "Unable to write to $INSTALL_FILE."
 		exit 2
 	fi
-	echo "# authorized_keys generated by ColtonDRG SSH Keystore script $SCRIPT_REV ($PROJECT_URL)" > $INSTALL_FILE
-	echo "# Generated from ColtonDRG/ssh-keystore commit `git rev-parse --short HEAD` on `date -u +%Y/%m/%d\ %H:%M`" >> $INSTALL_FILE
-	echo >> $INSTALL_FILE
-	cat *.pub >> $INSTALL_FILE
+	echo "# authorized_keys generated by ColtonDRG SSH Keystore script $SCRIPT_REV ($PROJECT_URL)" > "$INSTALL_FILE"
+	echo "# Generated from ColtonDRG/ssh-keystore commit $(git rev-parse --short HEAD) on $(date -u +%Y/%m/%d\ %H:%M)" >> "$INSTALL_FILE"
+	echo >> "$INSTALL_FILE"
+	cat *.pub >> "$INSTALL_FILE"
 	if [ -x "postinstall" ]; then
 		echo "Executing postinstall script."
 		export INSTALL_FILE="$INSTALL_FILE"
